it:
    #!/usr/bin/env bash
    set -eu

    for example in */; do
        if [ -d "$example" ] && [ -f "${example}main.libsonnet" ]; then
            echo "$example"
            ../../dist/jsonnet-kit bundle -i "${example}main.libsonnet" -o "${example}actual.libsonnet"

            if diff "${example}actual.libsonnet" "${example}expected.libsonnet" > /dev/null; then
                echo "Passed"
            else
                echo "Failed"
                diff "${example}actual.libsonnet" "${example}expected.libsonnet"
            fi
            echo
        fi
    done
