set fallback := true

test:
    #!/usr/bin/env bash

    devsonnet test

release: test
    #!/usr/bin/env bash

    devsonnet release -r https://github.com/marcbran/jsonnet.git -b "jsonnet-pkg" -p "jsonnet-pkg" "."
